### PR TITLE
use `8142` as default port for HTTPS

### PR DESCRIPTION
**Pull request by tyler36**
@simesy pointed out on slack that:

- README HTTPS examples use port `8142`
- `ddev status` shows HTTPS using port `8143`  

This inconsistency needs to be resolved.

This PR updates the service and launcher command to use `8142` on HTTPS.
`8142` is listed as the default port used on https://github.com/perftools/xhgui#installation-with-docker .

### CODE REVIEW

**Comment by tyler36** [comment]
Need to keep an eye on #31 will need updating if this proceeds.

**Review by rfay — APPROVED** [review]
It sure looks like it resolves the problem to me. Could also have changed the README.

**Comment by tyler36** [comment]
Do you think its better to change the port (this PR) or the docs?

DDEV services and addons generally use the default ports on HTTPS; so I went with logic here.

**Comment by rfay** [comment]
Default port on HTTPS is natural and normal. There is one exception (Solr) where HTTPS doesn't behave right for some reason, but best on all the others is HTTPS. 

I think either way you go (README or this) is fine.

**Pull request merged**
