### PR TITLE
Alert users to force adding xhprof_prepend.php

### PR DESCRIPTION
**Pull request by deviantintegral**
Without this, others cloning the repository won't have a working setup.

### CODE REVIEW

**Comment by rfay** [comment]
I don't believe that's correct (about forcing). DDEV automatically detects files on its list that do not have #ddev-generated and so will show them wanting to be committed. But it would have to be done right after the add-on is installed.

Bottom line is that we need a better way to manage this whole thing, perhaps not using the existing xhprof setup and doing our own.

**Comment by tyler36** [comment]
Any more thoughts here?

**Comment by rfay** [comment]
I think we'll want to re-think the defaults of how we're doing this in core ddev to make it a little more flexible here. 

There are lots of people who use xhprof as it is now, so we don't want to break them, but we should be able to figure this out with just a little work, and changing things in core is fine, or maybe a Dockerfile can handle it.

**Comment by deviantintegral** [comment]
I wonder if it would be OK for us to require the php-profiler package.

The challenge with the current API (imposed by xdebug) is that when you call xdebug_disable(), you get the profiler data and no one else can. But, if we used the above package, we could add a class that keeps a reference to the return'ed data, and returns that instead of calling xdebug_disable().

Something like

- 1st xdebug_disable() call stores the reference to the returned data, stores it in a class property.
- By default, subsequent calls return that same data.
- If you call enable() again, we set the property back to `[]` or null or whatever.

https://github.com/perftools/php-profiler/tree/main/src/Profilers

**Comment by tyler36** [comment]
@deviantintegral  is that a DDEV core or addon suggestion?

**Comment by deviantintegral** [comment]
I think it would have to be a ddev core suggestion, since it owns the current xhprof_prepend.php file.

**Comment by rfay** [comment]
Sorting this out is definitely a near term priority as the xhgui approach will be best for most people. If we don't have an issue going in core ddev, please open one, thx

**Comment by tyler36** [comment]
Issue created: https://github.com/ddev/ddev/issues/5698

**Comment by tyler36** [comment]
Thank you for this PR. 

After thinking about this, I came up with #28  which feels like a better solution. 
Happy to discuss before moving forward.

**Pull request closed without merging**
