### PR TITLE
Use official ddev-mongo addon

### LINKED ISSUE #13: Investigate using official mongo addon for database.
Comment by @rfay in https://github.com/tyler36/ddev-xhgui/pull/5#pullrequestreview-1723859678

> I am not sure why this uses its own mongo instead of depending on ddev-mongo, but ok...

### PR DESCRIPTION
**Pull request by tyler36**
This PR attempts to use the DDEV's mongo addon.

Fixes #13

## Notes
Currently, we use "percona/percona-server-mongodb:6.0-multi" for arm64 compatibility (00c1ccaf44e97392e014c34c904e77bd9ad4e260).

### CODE REVIEW

**Review by rfay — COMMENTED** [review]
You'll want to change the README to install ddev-mongo before installing ddev-xhgui

**Comment by rfay** [comment]
Test with `ddev get https://github.com/tyler36/ddev-xhgui/tarball/13-Investigate-using-official-mongo-addon-for-database`

**Comment by tyler36** [comment]
Fixes #20

**Comment by tyler36** [comment]
Added `ddev-mongo` to "Getting Started"

**Comment by rfay** [comment]
This is obsolete now right?

**Comment by tyler36** [comment]
Yes. This was an early solution to fix #14 

I was aiming to get #22 in though but ... "time".  

Closing in favor of #22

**Pull request closed without merging**
