### PR TITLE
Make add-on work w/o ddev-router, update tests

### PR DESCRIPTION
**Pull request by stasadev**
## The Issue

This add-on doesn't work in Gitpod.

## How This PR Solves The Issue

In terms of functionality, this add-on is similar to https://github.com/ddev/ddev-phpmyadmin
This PR contains recent fixes and improvements from `ddev-phpmyadmin`.

## Manual Testing Instructions

Test it locally and in Gitpod.

[Open in Gitpod](https://gitpod.io/#https://github.com/ddev/ddev)

```
ddev get https://github.com/ddev/ddev-xhgui/tarball/20240718_stasadev_norouter
ddev restart
ddev xhgui
```

### CODE REVIEW

**Comment by rfay** [comment]
For more generality we may want to move to using the router on gitpod/codespaces.

**Comment by tyler36** [comment]
Hmmm ... not sure if If like the `restart` in the health checks. I know it removes duplication, but personally, I prefer it in the test body. That way:

- it reminds me I need to restart after the install, 
- keeps the health checks clean; the check do just that, check, and 
- it doesn't force a restart if I need to run health checks multiple times in the same test.

If you prefer it _in_ the health check, I guess I'm OK with that.

**Comment by stasadev** [comment]
> If you prefer it _in_ the health check, I guess I'm OK with that.

It was a simple copy-paste to match the code in `ddev-phpmyadmin`.

I like your arguments, so I reverted this change.

**Comment by tyler36** [comment]
Works great! Thank you.

## Test

1. Click "Open in GItpod" link in description.
1. Add PR via tarball.

    ```shell
    ddev get https://github.com/ddev/ddev-xhgui/tarball/20240718_stasadev_norouter
    ```

1. Restart DDEV to apply addon.

    ```shell
    ddev restart
    ```

1. Confirm site is working.

    ```shell
    ddev launch
    ```

1. Configure Drupal umami following instructions in this repo's README.
  
1. Start profiling.

    ```shell
    ddev xhprof
    ```

1. Navigate site to generate a couple of profile reports.
1. Confirm launch command opens xhgui.

    ```shell
    ddev xhgui
    ```

image

**Pull request merged**
